import {EditorThemeI} from '@claspo/editor';

const primaryColor = '#303030';

export const SHOPIFY_THEME: EditorThemeI = {
  primaryFontFace: "Inter, -apple-system, BlinkMacSystemFont, 'San Francisco', 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif",
  primaryColor,
  secondaryColor: '#ffffff',
  successColor: '#047B5D',
  warningColor: '#FFB800',
  infoColor: '#005BD3',
  errorColor: '#C70A24',
  disabledFontColor: '#B5B5B5',
  primaryFontColor: '#303030',
  secondaryFontColor: '#616161',
  buttonFontWeight: '550',
  primaryButtonFontColor: '#FFFFFF',
  secondaryButtonFontColor: '#303030',
  secondaryButtonBorderColor: '#E3E3E3',
  secondaryButtonBorderWidth: '1px',
  buttonLoadingBackground: 'repeating-linear-gradient(60deg, transparent, transparent 40px, rgba(0,0,0,.3) 40px, rgba(0,0,0,.3) 80px), rgba(250,250,250,.5)',
  buttonHeight: '36px',
  buttonPadding: '8px 16px',
  buttonPaddingWithIcon: '8px 16px 8px 12px',
  inputLoadingBackground: 'repeating-linear-gradient(60deg, transparent, transparent 40px, rgba(0,0,0,.3) 40px, rgba(0,0,0,.3) 80px), rgba(250,250,250,.5)',
  textInputDefaultBorderColor: '#E3E3E3',
  textInputDefaultBorderWidth: '1px',
  textInputDefaultBackgroundColor: '#FFFFFF',
  textInputPadding: '8px 12px',
  checkboxDefaultBorderColor: '#8A8A8A',
  checkboxDefaultBorderWidth: '2px',
  checkboxDefaultBackgroundColor: '#FFFFFF',
  checkboxSelectedIconColor: '#FFFFFF',
  checkboxSize: '18px',
  radioButtonDefaultBackgroundColor: '#FFFFFF',
  switchDefaultBackgroundColor: '#B5B5B5',
  switchIconColor: '#FFFFFF',
  selectDefaultBorderColor: '#E3E3E3',
  selectDefaultBorderWidth: '1px',
  selectDefaultBackgroundColor: '#FFFFFF',
  selectPadding: '8px 12px',
  largeBorderRadius: '12px',
  smallBorderRadius: '8px',
  contextMenuSelectedBackgroundColor: '#F7F7F7',
  snackBarPositionTop: '65px',
  snackBarPadding: '12px 16px',
  darkerPrimaryColorKey: '#1A1A1A',
  lighterPrimaryColor: '#616161',
  veryLightPrimaryColor: '#F1F1F1',
  iconPickerColor: '#8051FF',
  notification: {
    padding: '12px 16px',
    borderRadius: '8px',
    boxShadow: '0px 4px 6px -2px rgba(0, 0, 0, 0.05), 0px 10px 15px -3px rgba(0, 0, 0, 0.1)',
    textColor: '#303030',
    warningBackgroundColor: '#FFF8DB',
    fontSize: '14px',
  },
  dialog: {
    titleFontSize: '16px',
    titleFontWeight: '650',
  },
  checkbox: {
    valueFontSize: '14px',
    valueFontColor: '#303030',
  },
  select: {
    filterBorderRadius: '8px',
    filterPadding: '8px 12px',
    filterIconPadding: '8px 12px 8px 8px',
  },
  input: {
    labelMargin: '0 0 4px 0',
    textInputTextareaPadding: '8px 12px',
    searchInputBackgroundIconColor: '#F1F1F1',
    searchInputBorderRadius: '8px',
    searchInputIconColorActive: '#303030',
  },
  dropdown: {
    borderRadius: '12px',
    padding: '8px',
    leftRightIndent: '8px',
  },
  editorOption: {
    customPrizeImageSize: '40px',
    borderDefaultColor: '#E3E3E3',
    borderClearButtonColor: '#C70A24',
    borderRadiusToggleButtons: '8px',
    descriptionFontSize: '12px',
    backgroundToggleButtonSelected: '#F1F1F1',
    backgroundToggleTextButtonSelected: '#FFFFFF',
    backgroundToggleButtonHover: '#E3E3E3',
    defaultBorder: '1px solid #E3E3E3',
  },
  editorPrizeOption: {
    gridTemplateColumns: '160px 415px 220px 20px',
    decrementIncrementGap: '1px',
    chancePseudoBorderRight: '',
    customEsInputFormWidth: '360px',
    confirmButtonBottomPadding: '16px 24px',
  },
  dropzone: {
    codeFont: "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace"
  },
  slidebar: {
    padding: '',
    margin: '0 0 20px 0',
    titleFontSize: '20px',
    titleFontWeight: '650',
  },
  editorPanel: {
    smallBorderRadius: '8px',
    rewardsInputWidth: '80px',
    errorNotificationBackgroundColor: '#FEE8EB',
    errorNotificationLeftPadding: '64px',
    tabsBackgroundColor: '#F1F1F1',
    tabBackgroundColor: '#FFFFFF',
    tabsDeviceBackgroundColor: '#FFFFFF',
    tabHoverBackgroundColor: '#E3E3E3',
    tabHoverColor: '',
    tabBorderRadius: '8px',
    borderLeftWidthSelected: '1px',
    borderTopWidthSelected: '1px',
    borderRightWidthSelected: '1px',
    borderBottomWidthSelected: '1px',
    borderBottomWidth: '0',
    tabPadding: '2px',
    tabHeaderPadding: '2px',
    tabButtonPadding: '6px 16px',
    tabHeight: '32px',
    tabGap: '4px',
  },
  editorInputs: {
    selectDefaultAlignItems: 'center',
    selectDefaultJustifyContent: 'space-between',
    selectInputDefaultMinHeight: '36px',
    selectInputDefaultLineHeight: '36px',
    inputDefaultMinWidth: '55px',
    inputSmallMinWidth: '50px',
    selectBodyWidth: '100%',
    searchInputBoxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
    searchInputBackgroundIconColor: '#FFFFFF',
    searchInputBorderRadius: '8px',
    searchInputBackgroundActiveColor: '#FFFFFF',
    searchInputBorderActiveColorHover: '2px solid #005BD3',
    searchInputBackgroundActiveMargin: '0',
    selectTextParamsWidth: '200px',
  },
};
