export default  {
    'en': 'Choose an option',
    'ru': 'Выберите опцию',
    'uk': 'Оберіть опцію',
    'es': 'Escoja una opción',
    'de': 'Wählen Sie eine Option',
    'fr': 'Choisissez une option',
    'it': 'Scegli un\'opzione',
    'pt': 'Escolha uma opção',
    "ro": "Alegeți o opțiune",
    "bg": "Изберете опция",
    "cs": "Vyberte si možnost",
    "el": "Διαλέξτε μια επιλογή",
    "nl": "Kies een optie",
    "pl": "Wybierz opcję",
    "sv": "Välj ett alternativ",
    "tr": "Bir seçenek belirleyin",
    "ar":  "اختر خيارًا",
};
